name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0, v2.0, etc.
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04 # Roda tudo dentro do Ubuntu 20.04 para garantir glibc 2.31
    
    steps:
    - name: Pre-requisites
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt-get update && apt-get install -y git zip unzip
        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Multiarch and Install Toolchain
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        dpkg --add-architecture arm64
        # Configura as sources para suportar pacotes amd64 e arm64 sem conflito
        sed -i 's/deb http/deb [arch=amd64] http/g' /etc/apt/sources.list
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal main restricted universe multiverse" >> /etc/apt/sources.list
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates main restricted universe multiverse" >> /etc/apt/sources.list
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-security main restricted universe multiverse" >> /etc/apt/sources.list
        apt-get update
        apt-get install -y --no-install-recommends \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu \
            cmake \
            make \
            pkg-config \
            file \
            libsdl2-dev:arm64 \
            libopenal-dev:arm64 \
            libgles2-mesa-dev:arm64

    - name: Build
      run: |
        mkdir -p build-r36s
        cd build-r36s
        cmake -DCMAKE_TOOLCHAIN_FILE="../toolchain-aarch64.cmake" -DR36S=ON -DCMAKE_BUILD_TYPE=Release -DFINAL_ENABLED=ON -DCMAKE_VERBOSE_MAKEFILE=OFF ../Code
        make -j$(nproc) Eld
        
    - name: Package Release
      run: |
        mkdir -p release/
        cp -r ports/eldritch release/
        cp build-r36s/Projects/Eld/Eld release/ports/eldritch/eldritch/
        cd release
        zip -r ../eldritch-r36s.zip ./*
        
    - name: Publish Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: eldritch-r36s.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
